services:
  - type: web
    name: shopcart
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn shopcart.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shopcart.settings
    
